### PR TITLE
Require Node.js 10.13 and upgrade most dependencies

### PR DESCRIPTION
**Pull request by realityking**
Node.js 10 is a necessary prequisite to upgrade `enhanced-resolve` and (hopefully) `node-module-lookup-amd` after dependents/node-module-lookup-amd#29 is merged.

### CODE REVIEW

**Comment by realityking** [comment]
I included the upgrade for `enhanced-resolve`. It still might make sense to hold off on pushing a new release until dependents/node-module-lookup-amd#29 is merged & released.

**Comment by mrjoelkemp** [comment]
Thanks for this @realityking. What does the latest enhanced-resolve bring us that's worth the upgrade? I'm not opposed to the breaking change, just curious what's the gain.

**Comment by realityking** [comment]
@mrjoelkemp Besides less dependencies and deduplication with web pack 5 (which to be honest, is what I'm after) the most significant improvement is that `exports` is correctly read from `package.json` files. More details in the changelog: https://github.com/webpack/enhanced-resolve/releases/tag/v5.0.0

**Comment by mrjoelkemp** [comment]
Thanks for the details @realityking. I merged your PR and did a major version bump to https://github.com/dependents/node-module-lookup-amd/. Let me know when all of the changes you want are in this PR and it's ready to be merged.

**Comment by realityking** [comment]
@mrjoelkemp `module-lookup-amd` is updated & PR is good to go. :)

**Comment by mrjoelkemp** [comment]
Thanks @realityking. Appreciate the help here. Just released a new major version.

**Pull request merged**
