### PR TITLE
Add an option to return .js file instead of .d.ts

### PR DESCRIPTION
**Pull request by jstevans**

### CODE REVIEW

**Comment by jstevans** [comment]
@mrjoelkemp Is there any work you'd like to see on this?

**Comment by mrjoelkemp** [comment]
Thanks for contributing. Is there any way to configure this behavior in a typescript config? Adding a flag here to skip .d.ts seems like a way of avoiding what the typescript resolver decides is the right file to map to the module. 

Generally, I'd prefer not to add and maintain new options (it just creates complexity in testing and readability) if there's a more language-specific configuration way of achieving the same outcome.

**Comment by jstevans** [comment]
It might exist, but I couldn't find it. I checked for such a config before submitting this PR, and couldn't find anything... The typescript resolver prefers the `.d.ts` files because that function seems to be primarily used for type-checking (e.g. [harnessLanguageService.ts](https://github.com/Microsoft/TypeScript/blob/75101d4b72b94d8158dabb249f9b6f969353110c/src/harness/harnessLanguageService.ts#L313) -- `tsc` doesn't seem to care too much about JS files without types :slightly_smiling_face: 

Totally get that. I'm pretty much using `filing-cabinet` to abstract out the `tsc` calls from my codebase, so this would be super useful for me. If this doesn't belong here, I'll probably end up having to reimplement this for myself :slightly_frowning_face:

**Comment by jstevans** [comment]
Hey @mrjoelkemp, is there more info you'd like? My project's been on the back-burner for a bit, but this is once again a pain point for me.

w.r.t. this second-guessing TSC -- TSC by default cares primarily about types rather than code, so it prefers `*.d.ts`. However, for tooling that wants to do interesting code transformations, the `*.js` files are far more relevant. This simply calls back into `ts.resolveJSModule`, which seems like the right TSC API.

**Comment by BPScott** [comment]
Wheee, dragging this out from the depths.

From [my pleasantly verbose comments on the PR that added tweaked this](https://github.com/dependents/node-filing-cabinet/pull/77#issuecomment-454898632): it sounds like the file with a`.js` extension, is included in the list of lookup locations. That seems like it would work.

I'm still not quire clear on the problem that you're is solving. Could you give an example of a set of files that result in the undesirable behaviour that you're trying to fix? "I have files A, B and C with the contents 1, 2 and 3. That gives be the the result X but I want the result Y instead" kinda thing.

**Comment by mrjoelkemp** [comment]
Thanks for this contribution and sorry for all of the delay and back and forth. I think the change is relatively harmless since it's opt-in. Would have loved a readme update documenting the option, but I'll merge.

**Pull request merged**
