### PR TITLE
Upgrade versions

### PR DESCRIPTION
**Pull request by akkumar**
Bunch of packages upgraded to latest versions , also restricted to their release version upgrades to keep them safe from future conflicts.

### CODE REVIEW

**Comment by mrjoelkemp** [comment]
@akkumar thanks for this. I've become a believer in caret version pegging for better deduping when installing packages. This was important for me when I was creating https://packagecontrol.io/packages/Dependents and needed to have flatter dep trees for Windows.

**Comment by akkumar** [comment]
@mrjoelkemp - I understand where you are coming for , especially regarding de-duping. 

I normally trust the release version upgrades most of the time to not break stuff, but with minor version changes (and definitely with major version changes) it becomes a bit harder to trust unless we, as package maintainers, run it ourselves to be sure of the same. It is more of the package maintenance style that I follow. 

Having said that, if you believe caret version pegging is still the way to go - then I can modify the patch appropriately while still upgrading the packages though. 

Let me know your choice either way.

**Comment by akkumar** [comment]
@mrjoelkemp - can you help review the changes now with carets in place ?

**Comment by akkumar** [comment]
@mrjoelkemp - let me know your thoughts on the latest version of the patch to see if it looks ok.

**Comment by mrjoelkemp** [comment]
Thanks @akkumar for your great work here!

**Pull request merged**
