### PR TITLE
Run more code in strict mode.

### PR DESCRIPTION
**Pull request by realityking**

### CODE REVIEW

**Comment by mrjoelkemp** [comment]
Thanks for contributing @realityking. I'm curious, what benefit does this give us?

**Comment by realityking** [comment]
Directly, only some safety guarantees, but those should also be provided by jshint. It also unlocks some ES2015 features (`const`, `let`, `class`) on Node.js 4.

I always add it to every file but not a big deal.

**Comment by mrjoelkemp** [comment]
Thanks for the details! It doesn't seem like it directly benefits us here. I don't have plans to introduce any es2015 code into this module (it used to target all the way down to Node 0.10 until my recent upgrade of the enhanced-resolve module for webpack resolution).

I'm happy to add this in when it becomes necessary. Hope that's cool.

**Comment by realityking** [comment]
Of course! Thanks for merging the other stuff 🙂

**Pull request closed without merging**
