### PR TITLE
Backfill test

### PR DESCRIPTION
**Pull request by mrjoelkemp**

### CODE REVIEW

**Comment by pahen** [comment]
The madge [build](https://travis-ci.org/pahen/madge/jobs/157802571) fails again after this fix. Seems to be a problem with resolving files when it has the .jsx extension. See "cabinet could not resolve /Users/patrik/Code/madge/test/jsx/other". Should we maybe allow the children to have the same extension as the parent when resolving?

```
  tree given filename: /Users/patrik/Code/madge/test/jsx/basic.jsx +1ms
  tree resolved filename: /Users/patrik/Code/madge/test/jsx/basic.jsx +1ms
  tree visited:  +0ms {}
  tree traversing /Users/patrik/Code/madge/test/jsx/basic.jsx +0ms
  tree extracted 2 dependencies:  +30ms [ 'react', './other' ]
  cabinet found a resolver for .jsx +1ms
  cabinet reusing the given ast +1ms
  cabinet using commonjs resolver for es6 +2ms
  cabinet adding /Users/patrik/Code/madge/test/jsx/node_modules to the require resolution paths +1ms
  cabinet could not resolve react +7ms
  cabinet resolved path for react:  +0ms
  tree cabinet result  +0ms
  tree filtering non-existent:  +0ms
  cabinet found a resolver for .jsx +0ms
  cabinet reusing the given ast +0ms
  cabinet using commonjs resolver for es6 +1ms
  cabinet adding /Users/patrik/Code/madge/test/jsx/node_modules to the require resolution paths +0ms
  cabinet could not resolve /Users/patrik/Code/madge/test/jsx/other +0ms
  cabinet resolved path for ./other:  +0ms
  tree cabinet result  +0ms
  tree filtering non-existent:  +0ms
  tree cabinet-resolved all dependencies:  +0ms []
  tree using filter function to filter out dependencies +0ms
  tree unfiltered number of dependencies: 0 +0ms
  tree filtered number of dependencies: 0 +0ms
  tree traversal complete +0ms {}
  tree object form of results requested +0ms
  tree final tree +0ms { '/Users/patrik/Code/madge/test/jsx/basic.jsx': {} }
```

**Comment by mrjoelkemp** [comment]
Thanks for reporting @pahen! Correct me if I'm wrong but shouldn't the import be ./other.jsx? Node wouldn't be able to resolve that import. Alternatively, if I remember correctly, there's a way of augmenting the file extensions that Node's resolver understands. 

Can you try the first suggestion of adding the explicit extension to the test? It seems more likely for that to be mandatory since users aren't configuring Node's resolution algorithm in their apps. 

Let me know what you find.

**Comment by pahen** [comment]
Thanks! You're right :) It's ok now after adding the extension to the import. All good! 💃

**Comment by mrjoelkemp** [comment]
Woot! Glad to hear it's passing now. :)

**Pull request merged**
